/**:
  ros__parameters:
    node_params:
      use_raw: [false, false, false, false, false, false] # per camera: if true, use raw image data, otherwise use compressed images
    model_params:
      plugins_path: "/home/autoware/ghq/github.com/Shin-kyoto/DL4AGX/AV-Solutions/vad-trt/app/demo/libplugins.so"
      default_command: 2  # 0: TURN RIGHT, 1: TURN LEFT, 2: KEEP FORWARD
      map_confidence_thresholds:
        divider: 0.9        # Confidence threshold for divider predictions
        ped_crossing: 0.9   # Confidence threshold for ped_crossing predictions  
        boundary: 0.9       # Confidence threshold for boundary predictions
      object_confidence_thresholds:
        car: 0.3
        truck: 0.3
        construction_vehicle: 0.3
        bus: 0.3
        trailer: 0.3
        barrier: 0.5
        motorcycle: 0.25
        bicycle: 0.25
        pedestrian: 0.3
        traffic_cone: 0.4
    sync_params:
      front_camera_id: 0  # ID of the front camera (anchor camera) for synchronization
      sync_tolerance_ms: 100.0  # Synchronization tolerance in milliseconds
